{{- if .Values.sidecar.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "cog-ai-model.sidecarName" . }}
  labels:
    {{- include "cog-ai-model.labels" . | nindent 4 }}
  {{- with .Values.sidecar.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  encryptedData:
    token: {{ .Values.sidecar.sealedSecrets.token | quote }}
  template:
    metadata:
      {{- with .Values.sidecar.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      name: {{ include "cog-ai-model.sidecarName" . }}
{{- end }}
---
{{- range .Values.sealedSecrets.secrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "cog-ai-model.fullname" $ }}-{{ .name }}
  labels:
    {{- include "cog-ai-model.labels" $ | nindent 4 }}
  {{- with .Values.sealedSecrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  encryptedData:
    {{ .name }}: {{ .value }}
  template:
    metadata:
      name: {{ include "cog-ai-model.fullname" $ }}-{{ .name }}
    {{- with .Values.sealedSecrets.annotations }}
    annotations:
      {{- toYaml . | nindent 8 }}
  {{- end }}
{{- end }}