{{- if .Values.sidecar.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "cog-ai-model.sidecarName" . }}
  labels:
    {{- include "cog-ai-model.labels" . | nindent 4 }}
  {{- with .Values.sidecar.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  encryptedData:
    token: {{ .Values.sidecar.sealedSecrets.token | quote }}
  template:
    metadata:
      {{- with .Values.sidecar.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      name: {{ include "cog-ai-model.sidecarName" . }}
{{- end }}