apiVersion: v1
kind: Service
metadata:
  name: {{ include "cog-ai-model.fullname" . }}
  labels:
    {{- include "cog-ai-model.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cog-ai-model.selectorLabels" . | nindent 4 }}
---
{{- if .Values.sidecar.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cog-ai-model.sidecarName" . }}
  labels:
    {{- include "cog-ai-model.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sidecar.service.type }}
  ports:
    - port: {{ .Values.sidecar.service.port }}
      targetPort: {{ .Values.sidecar.service.targetPort }}
      protocol: TCP
      name: auth
  selector:
    {{- include "cog-ai-model.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.nfs.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cog-ai-model.nfsSidecarName" . }}
  labels:
    {{- include "cog-ai-model.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nfs.service.type }}
  ports:
    - port: {{ .Values.nfs.service.port }}
      targetPort: {{ .Values.nfs.service.targetPort }}
      protocol: TCP
      name: nfs-server
  selector:
    {{- include "cog-ai-model.selectorLabels" . | nindent 4 }}
{{- end }}