name: check-codeowners

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install yq
        run: sudo snap install yq

      - name: Generate CODEOWNERS
        run: |
          ./scripts/check-codeowners.sh > .github/CODEOWNERS

      - name: Check CODEOWNERS for modifications
        run: git diff --exit-code || echo "::warning::There is at least one codeowner mismatch."
